### ISSUE TITLE
issueベースの開発 レビュー依頼

### ISSUE THREAD

**Issue by yu-ka3028** [yu-ka3028/GraduationProject_RUNTEQ#61]
お疲れ様です
issueのタスク分解を実施いたしました。
お忙しい中恐縮ですがご確認お願い申し上げます。

# MVPまでに実装予定の機能
- [ ]ユーザー登録機能(sorcery)
- [ ] メモ作成機能
- [ ] ジャンル/タグ機能
- [ ] 振り返りメモ作成機能
- [ ] メモ一覧表示機能
- [ ] メモの検索機能(Ransack)
- [ ] メモのステータスから達成率表示機能
- [ ] X共有機能

# 必要なページ
- [ ] 新規ユーザー登録
- [ ] ログイン
- [ ] マイページ(トップページ)
  - メモ作成（画面遷移なし）
- [ ] メモ一覧
- [ ] 振り返りメモ一覧

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
GitHubProjectsが確認できませんでしたので、こちらご確認いただいてもよろしいですか？
(作成してあるが見れない場合、private設定にしてあることが多いです。)
よろしくお願いします。
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/9fd4b48c924c0389b4649a42498fb340.png)](https://startup-technology.gyazo.com/9fd4b48c924c0389b4649a42498fb340)

**Comment by yu-ka3028** [comment]
お疲れ様です、大変失礼いたしましたPublicへ変更いたしました。
お手数おかけし申し訳ございません、ご確認お願い申し上げます。

# MVPまでに実装予定の機能
- [ ]ユーザー登録機能(sorcery)
- [ ] メモ作成機能
- [ ] ジャンル/タグ機能
- [ ] 振り返りメモ作成機能
- [ ] メモ一覧表示機能
- [ ] メモの検索機能(Ransack)
- [ ] メモのステータスから達成率表示機能
- [ ] X共有機能

# 必要なページ
- [ ] 新規ユーザー登録
- [ ] ログイン
- [ ] マイページ(トップページ)
  - メモ作成（画面遷移なし）
- [ ] メモ一覧
- [ ] 振り返りメモ一覧

**Comment by tarakish** [comment]
Issueの分割や各Issueでのタスク化、調査など大変良く書けていると思います👍
LGTMです！
MVPリリースに向けて開発頑張ってください。
